# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 91ba42298378d567afa140f68ccd5e3eb250b7dfc7e7ecb809a7d8160932d4bb54617a18400b9cc1fd2d33345e8850583619246baa350b9e6253d0fe6b0de698

test:
  secret_key_base: 14224e93cd81a478da4245562743dfb99b5b1037b67dd2a958eba292633d1f7d2f8dbe3598ef2d5659de2f58ed16c6ae576beee6c84e68359ff495a497203d5b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
